services:
  
  backend-api:
    build: 
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000" 
    volumes:
      - ./qdrant_db:/app/qdrant_db
    env_file:
      - .env 

  frontend-ui:
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "8501:8501" 
    environment:
      - API_URL=http://backend-api:8000/analyze
    depends_on:
      - backend-api 